#!/bin/bash

# Inspired by http://www.hascode.com/2012/12/creating-pre-commit-hooks-in-git-and-mercurial-prefix-commit-messages-for-featurestory-branches/

# This hook complemenets prepare-commit-msg that intellij does not respect
# Note: Intellij seems to run this with sh for some reason

set -eu
IFS=$'\n\t'

COMMIT_MSG="$(cat $1)"

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD || echo "undefined") # can be undefined without any commits
ISSUE_PATTERN='^[a-zA-Z]+[-][0-9]+'
# this is a hack since git-bash on windows does not support grep -o for some reason...
JIRA_ISSUE=$(echo "$BRANCH_NAME" | grep -E "$ISSUE_PATTERN" | sed -r "s/($ISSUE_PATTERN).*/\\1/")
JIRA_ISSUE_IN_MESSAGE=$(echo "$COMMIT_MSG" | grep "$JIRA_ISSUE" || true)

if [ -n "$JIRA_ISSUE" ] && [ -z "$JIRA_ISSUE_IN_MESSAGE" ]; then
    echo "Issue: $JIRA_ISSUE, Message: $COMMIT_MSG"
    echo "Branch contains JIRA-issue, but commit msg does not, this is not allowed!"
    exit 1
fi
