#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

if [[ "$(git log -1 --pretty=%B)" == "wip-stash" ]]; then
    echo "Popping work in progress on branch"
    git rsn 1
fi
