#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# Fix nvidia screen setup after sleep

metamode="DP-0: 2560x1440_165 +1920+0 {ForceCompositionPipeline=On}, USB-C-0: nvidia-auto-select +4480+120 {ForceCompositionPipeline=On}, DP-2: nvidia-auto-select +0+120 {ForceCompositionPipeline=On}"

nvidia-settings --assign CurrentMetaMode="$metamode"

sleep 3

# Sometimes we need to run twice
if ! nvidia-settings --query CurrentMetaMode | grep -q "+1920"; then
    nvidia-settings --assign CurrentMetaMode="$metamode"
fi
