#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

alias_name="$1"
alias_content="$(git config "alias.$alias_name")"
echo git config --global alias.$alias_name "'"$alias_content"'"
