#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

usage() {
    echo Usage: $0 new_email
    echo
    echo "Will update the email in all commits to this email"
}

if [[ -z "${1:-}" ]]; then
    usage
    exit 1
fi

set -x

email="$1"
git filter-branch -f --env-filter "GIT_AUTHOR_EMAIL='$email'; GIT_COMMITTER_EMAIL='$email'"

