#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

ARG="${1:-.}"
LINE="${2:-}"

if [[ "$ARG" =~ ^[0-9]+$ ]]; then
    uri="$(git github-url)/pull/$ARG"
else
    # cd to allow this from anywhere with absolue paths
    cd "$(dirname "$ARG")"

    relative_path="$(git rev-parse --show-prefix)$(basename "$ARG")"
    uri="$(git github-url)/tree/master/$relative_path"

    if [[ -n "$LINE" ]]; then
        uri="${uri}#L${LINE}"
    fi
fi

open "$uri"
