#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

FILE="${1:-.}"
LINE="${2:-}"

# cd to allow this from anywhere with absolue paths
cd "$(dirname "$FILE")"

relative_path="$(git rev-parse --show-prefix)$(basename "$FILE")"
uri="$(git github-url)/tree/master/$relative_path"

if [[ -n "$LINE" ]]; then
    uri="${uri}#L${LINE}"
fi

open "$uri"
