#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
IFS=$'\n\t'
set -euo pipefail

if [[ -n "$(git diff --cached | grep "NOCOMMIT")" ]]; then
    echo "Forbidden content (NOCOMMIT) found in commit (override with --no-verify)"
    exit 1
fi
